include $(top_srcdir)/common.am

bin_PROGRAMS    = spm25a spm25m spm25p
spm25a_SOURCES  = pm25_speci_a.F90
spm25m_SOURCES  = pm25_speci_m.F90
spm25p_SOURCES  = pm25_speci_p.F90

spm25a_FCFLAGS  = $(OPT2_FCFLAGS) $(FC_COMMON)
spm25m_FCFLAGS  = $(OPT2_FCFLAGS) $(FC_COMMON)
spm25p_FCFLAGS  = $(OPT2_FCFLAGS) $(FC_COMMON)
