include $(top_srcdir)/common.am

bin_PROGRAMS   = carr vial agrega
carr_SOURCES   = suma_carretera.F90
vial_SOURCES   = suma_vialidades.F90
agrega_SOURCES = agrega.f90

carr_FCFLAGS   = $(OPT2_FCFLAGS) $(FC_COMMON)
vial_FCFLAGS   = $(OPT2_FCFLAGS) $(FC_COMMON)
agrega_FCFLAGS = $(OPT2_FCFLAGS) $(FC_COMMON)
